#!/usr/bin/env python3
"""Scale stress test: does the routing mechanism still behave sensibly far
outside every scale this program has tested so far (2-6 robots)?

Requested by the user directly: a 5x-larger warehouse with 100 robots, and
a 10x-larger ("city-scale") deployment with 200 robots. Neither scale has
appeared anywhere else in this program. The station layout is generated by
`raca_core.stations.build_station_table(scale)`, the SAME generator that
produces the real, calibration-relevant layout at scale=1.0, just run with
a bigger range - not a fabricated new geometry.

This is exploratory, N=1 per scenario (one seed), not a statistically
powered claim - consistent with how this program treats single-run
scale/stress checks elsewhere (Phase 12). The goal is to see whether
anything breaks (crashes, deadlocks, runaway runtime) and how the
LLM-invocation rate and mean tasks/robot shift, not to produce a new
headline percentage.

    python raca/tools/run_scale_stress_test.py
"""
from __future__ import annotations

import random
import statistics
import sys
import time
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "raca"))

from raca_core.config import build_backend  # noqa: E402
from raca_core.stations import build_station_table  # noqa: E402
from raca_worlds.lightweight_world import LightweightWorld  # noqa: E402

DURATION_SEC = 300.0  # 5 minutes simulated time, longer than the N=20 campaign's 60s since more robots means more contention to settle
LLM_CONFIG = {"backend": "mock", "fixed_cost": 0.9}
ROUTER_NAMES = ["always_deterministic", "always_llm", "adaptive_router"]

SCENARIOS = [
    {"name": "5x_warehouse_100_robots", "scale": 5.0, "num_robots": 100},
    {"name": "10x_city_200_robots", "scale": 10.0, "num_robots": 200},
    {"name": "50x_city_1000_robots", "scale": 50.0, "num_robots": 1000},
]


def _start_positions(num_robots: int, scale: float, seed: int) -> dict:
    rng = random.Random(seed * 7919)
    x_bound = 6.5 * scale
    y_bound = 8.5 * scale
    return {
        f"robot{i}": (rng.uniform(-x_bound, x_bound), rng.uniform(-y_bound, y_bound))
        for i in range(1, num_robots + 1)
    }


def run_one(router_name: str, scenario: dict, seed: int = 1) -> dict:
    num_robots = scenario["num_robots"]
    scale = scenario["scale"]
    _, stations_by_side = build_station_table(scale)
    robot_ids = [f"robot{i}" for i in range(1, num_robots + 1)]
    router_ref = []

    def factory():
        router = build_backend({"backend": router_name, "llm_config": LLM_CONFIG})
        router_ref.append(router)
        return router

    world = LightweightWorld(
        robot_ids=robot_ids,
        seed=seed,
        backend_factory=factory,
        start_positions=_start_positions(num_robots, scale, seed),
        stations_by_side=stations_by_side,
    )
    wall_start = time.perf_counter()
    world.run_until(DURATION_SEC)
    wall_elapsed = time.perf_counter() - wall_start
    summary = world.summary()

    total_llm = sum(getattr(r, "stats", None).llm_decisions for r in router_ref if hasattr(r, "stats"))
    total_calls = sum(getattr(r, "stats", None).total for r in router_ref if hasattr(r, "stats"))

    return {
        "router": router_name,
        "scenario": scenario["name"],
        "num_robots": num_robots,
        "num_stations": len(stations_by_side["input"]) + len(stations_by_side["output"]),
        "tasks_completed": summary["total_tasks_completed"],
        "tasks_per_robot": summary["total_tasks_completed"] / num_robots,
        "llm_invocation_rate": (total_llm / total_calls) if total_calls else 0.0,
        "wall_clock_sec": wall_elapsed,
    }


def run() -> int:
    print("scale stress test: does the routing mechanism hold up far outside the 2-6 robot range tested elsewhere?\n")
    print(f"duration={DURATION_SEC}s simulated, N=1 seed per (scenario, router) - exploratory, not statistically powered\n")

    all_rows = []
    for scenario in SCENARIOS:
        print(f"### {scenario['name']} (scale={scenario['scale']}x, {scenario['num_robots']} robots)\n")
        header = "| Router | N robots | N stations | Tasks completed | Tasks/robot | LLM rate | Wall clock |"
        sep = "|---|---:|---:|---:|---:|---:|---:|"
        print(header)
        print(sep)
        rows = []
        for router_name in ROUTER_NAMES:
            row = run_one(router_name, scenario)
            rows.append(row)
            all_rows.append(row)
            print(
                f"| {router_name} | {row['num_robots']} | {row['num_stations']} | "
                f"{row['tasks_completed']} | {row['tasks_per_robot']:.3f} | "
                f"{row['llm_invocation_rate']:.4f} | {row['wall_clock_sec']:.2f}s |"
            )
        print()
        adaptive = next(r for r in rows if r["router"] == "adaptive_router")
        always_llm = next(r for r in rows if r["router"] == "always_llm")
        always_det = next(r for r in rows if r["router"] == "always_deterministic")
        task_diff = adaptive["tasks_completed"] - always_llm["tasks_completed"]
        rate_diff = adaptive["llm_invocation_rate"] - always_llm["llm_invocation_rate"]
        print(f"  adaptive_router vs always_llm: task-count diff {task_diff:+d}, LLM-rate diff {rate_diff:+.4f}")
        print(f"  adaptive_router vs always_deterministic: task-count diff {adaptive['tasks_completed'] - always_det['tasks_completed']:+d}")
        print(f"  contention ratio (robots per station): {scenario['num_robots'] / (len(build_station_table(scenario['scale'])[1]['input']) * 2):.2f}")
        print()

    print("(N=1 per cell - a single seed at each scale, exploratory only. No statistical claim is made here;")
    print(" compare against the N=20, 2-robot campaign in Phase 13 / RACA-PAPER/data/phase13_campaign_N20.txt")
    print(" for the statistically powered result at the scale this program actually validated.)")
    return 0


if __name__ == "__main__":
    raise SystemExit(run())
